word_list = [
    "APPLE", "BANANA", "ORANGE", "GRAPE", "PEACH", "CHERRY", "MANGO", "LEMON", "LIME", "MELON",
    "KIWI", "PAPAYA", "COCONUT", "APRICOT", "PLUM", "PEAR", "FIG", "DATE", "RAISIN", "BERRY",
    "TOMATO", "CARROT", "POTATO", "ONION", "GARLIC", "PEPPER", "LETTUCE", "SPINACH", "BROCCOLI", "CABBAGE",
    "PUMPKIN", "RADISH", "TURNIP", "BEET", "CELERY", "CUCUMBER", "ZUCCHINI", "SQUASH", "GINGER", "BASIL",
    "THYME", "OREGANO", "PARSLEY", "CINNAMON", "VANILLA", "CHOCOLATE", "COOKIE", "BISCUIT", "MUFFIN", "PANCAKE",
    "WAFFLE", "OMELET", "PIZZA", "BURGER", "SANDWICH", "NOODLE", "PASTA", "RICE", "CEREAL", "YOGURT",
    "CHEESE", "BUTTER", "HONEY", "SUGAR", "SALT", "COFFEE", "TEA", "COCOA", "SMOOTHIE", "LEMONADE",
    "WATER", "SODA", "JUICE", "KETTLE", "TOASTER", "BLENDER", "SKILLET", "SAUCEPAN", "OVEN", "FREEZER",
    "FRIDGE", "CUPBOARD", "PANTRY", "KITCHEN", "GARDEN", "FOREST", "DESERT", "ISLAND", "MOUNTAIN", "VALLEY",
    "RIVER", "OCEAN", "BEACH", "SUNSET", "SUNRISE", "RAINBOW", "THUNDER", "LIGHTNING", "BREEZE", "SHADOW"
]
